import './globals.css'
import {inter, racing_sans_one, roboto_mono} from "./styles/fonts"

export const metadata = {
  title: 'Stamurai | Task Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} ${racing_sans_one.variable} ${roboto_mono.variable}`}>
      <body>{children}</body>
    </html>
  )
}
